In [1]:
#Library Imports
import numpy as np
import pandas as pd
import math
import os
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error

#######딥러닝 라이브러리##########
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Reshape, GRU, RNN

tf.keras.backend.set_floatx('float64')

In [214]:
train=pd.read_csv('./Data_for_Modeling/Train_for_model.csv')
#train['date_time'] = pd.to_datetime(train['date_time'])

test=pd.read_csv('./Data_for_Modeling/Test_for_model.csv')
#test['date_time'] = pd.to_datetime(test['date_time'])

submission=pd.read_csv('sample_submission.csv', encoding = 'cp949')

In [215]:
#train.shape 122400 X 10
#60개의 건물 X 85일 24시간 =122400
train

,num,date_time,전력사용량(kWh),기온(°C),풍속(m/s),습도(%),강수량(mm),일조(hr),비전기냉방설비운영,태양광보유
0,1,2020-06-01 00,8179.056,17.6,2.5,92.0,0.8,0.0,0,0
1,1,2020-06-01 01,8135.640,17.7,2.9,91.0,0.3,0.0,0,0
2,1,2020-06-01 02,8107.128,17.5,3.2,91.0,0.0,0.0,0,0
3,1,2020-06-01 03,8048.808,17.1,3.2,91.0,0.0,0.0,0,0
4,1,2020-06-01 04,8043.624,17.0,3.3,92.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
118075,60,2020-08-21 19,3780.000,27.0,1.9,77.0,0.0,0.1,1,1
118076,60,2020-08-21 20,3691.440,26.0,2.6,82.0,0.0,0.0,1,1
118077,60,2020-08-21 21,3532.896,25.2,2.2,83.0,0.0,0.0,1,1
118078,60,2020-08-21 22,3411.504,24.9,2.4,84.0,0.0,0.0,1,1
118079,60,2020-08-21 23,3158.352,24.4,1.9,85.0,0.0,0.0,1,1

In [216]:
#test.shape 10080 X 9
#60개의 건물 X 7일 24시간 =10080
test

,num,date_time,전력사용량(kWh),기온(°C),풍속(m/s),습도(%),강수량(mm),일조(hr),비전기냉방설비운영,태양광보유
0,1,2020-08-22 00,8646.264,25.2,1.9,87,0.0,0.0,0,0
1,1,2020-08-22 01,8637.192,25.0,2.0,86,0.0,0.0,0,0
2,1,2020-08-22 02,8616.456,25.0,1.4,86,0.0,0.0,0,0
3,1,2020-08-22 03,8592.480,24.7,1.8,86,0.0,0.0,0,0
4,1,2020-08-22 04,8570.448,24.4,1.7,87,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...
4315,60,2020-08-24 19,4114.368,27.8,2.3,68,0.0,0.7,1,1
4316,60,2020-08-24 20,3975.696,27.3,1.2,71,0.0,0.0,1,1
4317,60,2020-08-24 21,3572.208,27.3,1.8,71,0.0,0.0,1,1
4318,60,2020-08-24 22,3299.184,27.1,1.8,74,0.0,0.0,1,1
4319,60,2020-08-24 23,3204.576,27.1,2.6,75,0.0,0.0,1,1

# **딥러닝 모델(전력사용량만 변수로 사용)**

In [217]:
import datetime

In [218]:
#train=train.drop(columns=["acc_x", "acc_y", "acc_z","gy_x", "gy_y", "gy_z"])
#test=test.drop(columns=["acc_x", "acc_y", "acc_z","gy_x", "gy_y", "gy_z"])

train=train.drop(train.iloc[:,6:], axis=1)
test=test.drop(test.iloc[:,6:], axis=1)

In [219]:
# 시간, 요일, 주말여부(new!) 추가
def time(x):
    return int(x[-2:])
train['time']=train['date_time'].apply(lambda x: time(x))
test['time']=test['date_time'].apply(lambda x: time(x))

# 평일=0~4, 주말=5~6
def weekday(x):
    return pd.to_datetime(x[:10]).weekday()
train['weekday']=train['date_time'].apply(lambda x :weekday(x))
test['weekday']=test['date_time'].apply(lambda x :weekday(x))

# 평일=0, 주말=1
train['weekend']=train['weekday'].apply(lambda x: 0 if x < 4 else 1)
test['weekend']=test['weekday'].apply(lambda x: 0 if x < 4 else 1)

train['THI'] = 9/5*train['기온(°C)'] - 0.55*(1-train['습도(%)']/100)*(9/5*train['기온(°C)']-26)+32
test['THI'] = 9/5*test['기온(°C)'] - 0.55*(1-test['습도(%)']/100)*(9/5*test['기온(°C)']-26)+32

In [220]:
from sklearn.cluster import k_means
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

d_list = []
for i in range(1, 61):
    d = train[train['num'] == i].copy()
    d['전력사용량(kWh)'] = scaler.fit_transform(d['전력사용량(kWh)'].values.reshape(-1,1))
    d_ = d.groupby(['weekday', 'time'])['전력사용량(kWh)'].mean().unstack()
    d_list.append(d_.to_numpy())

In [221]:
##############전력사용량(kWh) 정규화####################################

mini=train.iloc[:,2].min()
size=train.iloc[:,2].max()-train.iloc[:,2].min()
train.iloc[:,2]=(train.iloc[:,2]-mini)/size


col=train.columns
scaler = StandardScaler()

train.iloc[:,3:]= scaler.fit_transform(train.iloc[:,3:])
train = pd.DataFrame(data = train,columns =col)

test.iloc[:,3:]= scaler.transform(test.iloc[:,3:])
test = pd.DataFrame(data = test,columns =col)

In [223]:
train['num']

0          1
1          1
2          1
3          1
4          1
          ..
118075    60
118076    60
118077    60
118078    60
118079    60
Name: num, Length: 118080, dtype: int64

In [224]:
a = [1,3,5,9,15,19,20,21,49,50,51]

# 우선 필요한 함수를 생성한다
def get_category(num):
    type_e = ''
    if num == 15: type_e = 0
    elif num == 3 or 5: type_e = 1
    elif num == 1 or 9: type_e = 2
    elif num == 19 or 20 or 21 or 49 or 50 or 51: type_e = 3
    else : type_e = 4

    return type_e

# lambda 식에 위에서 생성한 함수를 반환값으로 지정한다.
train['new_group'] = train['num'].apply(lambda x : get_category(x))
test['new_group'] = test['num'].apply(lambda x : get_category(x))
    
    
train

,num,date_time,전력사용량(kWh),기온(°C),풍속(m/s),습도(%),time,weekday,weekend,THI,new_group
0,1,2020-06-01 00,0.461072,-1.931816,0.218064,0.755834,-1.661325,-1.481542,-0.841625,-2.072800,1
1,1,2020-06-01 01,0.458624,-1.902416,0.480203,0.691868,-1.516862,-1.481542,-0.841625,-2.043530,1
2,1,2020-06-01 02,0.457017,-1.961215,0.676807,0.691868,-1.372399,-1.481542,-0.841625,-2.115145,1
3,1,2020-06-01 03,0.453729,-2.078813,0.676807,0.691868,-1.227936,-1.481542,-0.841625,-2.258374,1
4,1,2020-06-01 04,0.453437,-2.108212,0.742342,0.755834,-1.083473,-1.481542,-0.841625,-2.288887,1
...,...,...,...,...,...,...,...,...,...,...,...
118075,60,2020-08-21 19,0.213087,0.831729,-0.175145,-0.203656,1.083473,0.534830,1.188177,0.922344,1
118076,60,2020-08-21 20,0.208095,0.537735,0.283598,0.116174,1.227936,0.534830,1.188177,0.712992,1
118077,60,2020-08-21 21,0.199157,0.302540,0.021459,0.180140,1.372399,0.534830,1.188177,0.463737,1
118078,60,2020-08-21 22,0.192314,0.214341,0.152529,0.244106,1.516862,0.534830,1.188177,0.382951,1
118079,60,2020-08-21 23,0.178043,0.067344,-0.175145,0.308072,1.661325,0.534830,1.188177,0.231794,1

In [225]:
train=train.drop(train.iloc[:,:2], axis=1)
test=test.drop(test.iloc[:,:2], axis=1)
train=train.drop(train.iloc[:,1:5], axis=1)
test=test.drop(test.iloc[:,1:5], axis=1)

In [226]:
train

        전력사용량(kWh)   weekday   weekend       THI  new_group
0         0.461072 -1.481542 -0.841625 -2.072800          1
1         0.458624 -1.481542 -0.841625 -2.043530          1
2         0.457017 -1.481542 -0.841625 -2.115145          1
3         0.453729 -1.481542 -0.841625 -2.258374          1
4         0.453437 -1.481542 -0.841625 -2.288887          1
...            ...       ...       ...       ...        ...
118075    0.213087  0.534830  1.188177  0.922344          1
118076    0.208095  0.534830  1.188177  0.712992          1
118077    0.199157  0.534830  1.188177  0.463737          1
118078    0.192314  0.534830  1.188177  0.382951          1
118079    0.178043  0.534830  1.188177  0.231794          1

[118080 rows x 5 columns]

In [236]:
####################################################

input_window = 996 #임의의 수
output_window = 24 #168 7일 24시간
window = 12 #window는 12시간 마다는 12시간 마다
num_features = 5 #베이스라인은 feature를 하나만 사용했습니다.
num_power = 60 #건물개수
end_=168 
lstm_units=32
dropout=0.2
EPOCH=50
BATCH_SIZE=200

In [230]:
#train을 tensor로 변경 (60, 24*82, 1)
train_x=tf.reshape(train.values, [num_power, -1, num_features])
print(f'train_x.shape:{train_x.shape}')

train_x.shape:(60, 1968, 5)

In [231]:
#train_window_x np.zeros를 만듬 (60, 79, 996, 8)
train_window_x= np.zeros(( train_x.shape[0], (train_x.shape[1]-(input_window + output_window))//window, input_window, num_features)) 
train_window_y= np.zeros(( train_x.shape[0], (train_x.shape[1]-(input_window + output_window))//window, output_window, num_features))
print(f'train_window_x.shape:{train_window_x.shape}')
print(f'train_window_y.shape:{train_window_y.shape}')

train_window_x.shape:(60, 79, 996, 5)
train_window_y.shape:(60, 79, 24, 5)

In [232]:
#train_window_x에 train값 채워넣기
for example in range(train_x.shape[0]):
    
    for start in range(0, train_x.shape[1]-(input_window+output_window), window):
        end=start+input_window
        train_window_x[example, start//window, :] = train_x[example, start: end               , :]
        train_window_y[example, start//window, :] = train_x[example, end  : end+ output_window, :]

In [233]:
#new_train_x, reshape통해 lstm에 알맞은 형태로 집어넣기
new_train_x=tf.reshape(train_window_x, [-1, input_window, num_features])
new_train_y=tf.reshape(train_window_y, [-1, output_window,num_features])
print(f'new_train_x.shape:{new_train_x.shape}')
print(f'new_train_y.shape:{new_train_y.shape}')

new_train_x.shape:(4740, 996, 5)
new_train_y.shape:(4740, 24, 5)

In [234]:
from sklearn.model_selection import KFold
from numpy.random import seed

In [235]:
# folds=3
# repeats=3
# epochsize=20
# drop=0.5
# kfold = KFold(n_splits=folds, shuffle=True)

# save_best_only=tf.keras.callbacks.ModelCheckpoint(filepath="lstm_model.h5", monitor='val_loss', save_best_only=True)
# early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=20)
# reduceLR = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10)


# for k in range(repeats):
#     for train_ind, test_ind in kfold.split(new_train_x, new_train_y):
#         seed(2021)
#         tf.random.set_seed(2021)

#         input_layer = keras.layers.Input(new_train_x.shape[1:])
#         model1 = keras.layers.LSTM(32, return_sequences=False, recurrent_dropout=dropout)(input_layer)

#         output_layer = keras.layers.Dense(output_window * num_features, kernel_initializer=tf.initializers.zeros())(model1)

#         model = keras.models.Model(inputs=input_layer, outputs=output_layer)


#         model.compile(loss='mae',
#                       optimizer='rmsprop',
#                       metrics=['mae'])

#         model.fit(new_train_x, new_train_y, epochs=EPOCH, batch_size=BATCH_SIZE, validation_split = 0.2, verbose=1,
#           callbacks=[early_stop, save_best_only , reduceLR])

        
        
        
#     print(f'\n\n********    {k+1}번 러닝 완료    *********\n\n')

In [237]:
#####층 쌓기###########


model=Sequential([
LSTM(lstm_units, return_sequences=False, recurrent_dropout=dropout),
Dense(output_window * num_features, kernel_initializer=tf.initializers.zeros()), 
Reshape([output_window, num_features])
])
#######Compile 구성하기################


model.compile(optimizer='adam', loss='mae', metrics=['mae'])
# # 에포크가 끝날 때마다 점(.)을 출력해 훈련 진행 과정을 표시합니다
# class PrintDot(tf.keras.callbacks.Callback):
#     def on_epoch_end(self, epoch, logs):
#         if epoch % 10 == 0: print('')
#         print('.', end='')

#가장 좋은 성능을 낸 val_loss가 적은 model만 남겨 놓았습니다.
save_best_only=tf.keras.callbacks.ModelCheckpoint(filepath="lstm_model.h5", monitor='val_loss', save_best_only=True)


early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=20)

#검증 손실이 10epoch 동안 좋아지지 않으면 학습률을 0.1 배로 재구성하는 명령어입니다.
reduceLR = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=4)

######################
model.fit(new_train_x, new_train_y, epochs=EPOCH, batch_size=BATCH_SIZE, validation_split = 0.2, verbose=1,
          callbacks=[early_stop, save_best_only , reduceLR])

WARNING:tensorflow:Layer lstm_2 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Epoch 1/50
19/19 [==============================] - 48s 2s/step - loss: 0.7039 - mae: 0.7039 - val_loss: 0.7297 - val_mae: 0.7297
Epoch 2/50
19/19 [==============================] - 47s 2s/step - loss: 0.5614 - mae: 0.5614 - val_loss: 0.5894 - val_mae: 0.5894
Epoch 3/50
19/19 [==============================] - 45s 2s/step - loss: 0.3952 - mae: 0.3952 - val_loss: 0.4807 - val_mae: 0.4807
Epoch 4/50
19/19 [==============================] - 46s 2s/step - loss: 0.3098 - mae: 0.3098 - val_loss: 0.4027 - val_mae: 0.4027
Epoch 5/50
19/19 [==============================] - 46s 2s/step - loss: 0.2652 - mae: 0.2652 - val_loss: 0.3852 - val_mae: 0.3852
Epoch 6/50
19/19 [==============================] - 45s 2s/step - loss: 0.2592 - mae: 0.2592 - val_loss: 0.3828 - val_mae: 0.3828
Epoch 7/50
19/19 [==============================] - 47s 2s/step - loss: 0.2570 - mae: 0.2570 - val_loss: 0.3786 - val_mae: 0.3786
Epoch 8/50
19/19 [==============================] - 45s 2s/step - loss: 0.2540 - mae: 0.2540 - val_loss: 0.3717 - val_mae: 0.3717
Epoch 9/50
19/19 [==============================] - 46s 2s/step - loss: 0.2475 - mae: 0.2475 - val_loss: 0.3611 - val_mae: 0.3611
Epoch 10/50
19/19 [==============================] - 46s 2s/step - loss: 0.2337 - mae: 0.2337 - val_loss: 0.3425 - val_mae: 0.3425
Epoch 11/50
19/19 [==============================] - 46s 2s/step - loss: 0.2161 - mae: 0.2161 - val_loss: 0.3178 - val_mae: 0.3178
Epoch 12/50
19/19 [==============================] - 46s 2s/step - loss: 0.2067 - mae: 0.2067 - val_loss: 0.3053 - val_mae: 0.3053
Epoch 13/50
19/19 [==============================] - 45s 2s/step - loss: 0.1948 - mae: 0.1948 - val_loss: 0.2967 - val_mae: 0.2967
Epoch 14/50
19/19 [==============================] - 45s 2s/step - loss: 0.1892 - mae: 0.1892 - val_loss: 0.2813 - val_mae: 0.2813
Epoch 15/50
19/19 [==============================] - 46s 2s/step - loss: 0.1879 - mae: 0.1879 - val_loss: 0.2671 - val_mae: 0.2671
Epoch 16/50
19/19 [==============================] - 45s 2s/step - loss: 0.1805 - mae: 0.1805 - val_loss: 0.2521 - val_mae: 0.2521
Epoch 17/50
19/19 [==============================] - 45s 2s/step - loss: 0.1738 - mae: 0.1738 - val_loss: 0.2285 - val_mae: 0.2285
Epoch 18/50
19/19 [==============================] - 45s 2s/step - loss: 0.1676 - mae: 0.1676 - val_loss: 0.2079 - val_mae: 0.2079
Epoch 19/50
19/19 [==============================] - 45s 2s/step - loss: 0.1635 - mae: 0.1635 - val_loss: 0.1968 - val_mae: 0.1968
Epoch 20/50
19/19 [==============================] - 45s 2s/step - loss: 0.1597 - mae: 0.1597 - val_loss: 0.1849 - val_mae: 0.1849
Epoch 21/50
19/19 [==============================] - 45s 2s/step - loss: 0.1571 - mae: 0.1571 - val_loss: 0.1744 - val_mae: 0.1744
Epoch 22/50
19/19 [==============================] - 46s 2s/step - loss: 0.1544 - mae: 0.1544 - val_loss: 0.1661 - val_mae: 0.1661
Epoch 23/50
19/19 [==============================] - 45s 2s/step - loss: 0.1523 - mae: 0.1523 - val_loss: 0.1580 - val_mae: 0.1580
Epoch 24/50
19/19 [==============================] - 45s 2s/step - loss: 0.1503 - mae: 0.1503 - val_loss: 0.1514 - val_mae: 0.1514
Epoch 25/50
19/19 [==============================] - 45s 2s/step - loss: 0.1483 - mae: 0.1483 - val_loss: 0.1448 - val_mae: 0.1448
Epoch 26/50
19/19 [==============================] - 46s 2s/step - loss: 0.1466 - mae: 0.1466 - val_loss: 0.1420 - val_mae: 0.1420
Epoch 27/50
19/19 [==============================] - 45s 2s/step - loss: 0.1450 - mae: 0.1450 - val_loss: 0.1367 - val_mae: 0.1367
Epoch 28/50
19/19 [==============================] - 45s 2s/step - loss: 0.1436 - mae: 0.1436 - val_loss: 0.1346 - val_mae: 0.1346
Epoch 29/50
19/19 [==============================] - 45s 2s/step - loss: 0.1423 - mae: 0.1423 - val_loss: 0.1332 - val_mae: 0.1332
Epoch 30/50
19/19 [==============================] - 45s 2s/step - loss: 0.1407 - mae: 0.1407 - val_loss: 0.1297 - val_mae: 0.1297
Epoch 31/50
19/19 [==============================] - 46s 2s/step - loss: 0.1389 - mae: 0.1389 - val_loss: 0.1282 - val_mae: 0.1282
Epoch 32/50
19/19 [==============================] - 45s 2s/step - loss: 0.1375 - mae: 0.1375 - val_loss: 0.1256 - val_mae: 0.1256
Epoch 33/50
19/19 [==============================] - 45s 2s/step - loss: 0.1357 - mae: 0.1357 - val_loss: 0.1248 - val_mae: 0.1248
Epoch 34/50
19/19 [==============================] - 45s 2s/step - loss: 0.1339 - mae: 0.1339 - val_loss: 0.1230 - val_mae: 0.1230
Epoch 35/50
19/19 [==============================] - 45s 2s/step - loss: 0.1325 - mae: 0.1325 - val_loss: 0.1214 - val_mae: 0.1214
Epoch 36/50
19/19 [==============================] - 47s 2s/step - loss: 0.1304 - mae: 0.1304 - val_loss: 0.1197 - val_mae: 0.1197
Epoch 37/50
19/19 [==============================] - 46s 2s/step - loss: 0.1287 - mae: 0.1287 - val_loss: 0.1177 - val_mae: 0.1177
Epoch 38/50
19/19 [==============================] - 45s 2s/step - loss: 0.1263 - mae: 0.1263 - val_loss: 0.1175 - val_mae: 0.1175
Epoch 39/50
19/19 [==============================] - 46s 2s/step - loss: 0.1245 - mae: 0.1245 - val_loss: 0.1174 - val_mae: 0.1174
Epoch 40/50
19/19 [==============================] - 47s 2s/step - loss: 0.1225 - mae: 0.1225 - val_loss: 0.1164 - val_mae: 0.1164
Epoch 41/50
19/19 [==============================] - 47s 2s/step - loss: 0.1202 - mae: 0.1202 - val_loss: 0.1153 - val_mae: 0.1153
Epoch 42/50
19/19 [==============================] - 47s 2s/step - loss: 0.1187 - mae: 0.1187 - val_loss: 0.1150 - val_mae: 0.1150
Epoch 43/50
19/19 [==============================] - 46s 2s/step - loss: 0.1166 - mae: 0.1166 - val_loss: 0.1145 - val_mae: 0.1145
Epoch 44/50
19/19 [==============================] - 46s 2s/step - loss: 0.1150 - mae: 0.1150 - val_loss: 0.1143 - val_mae: 0.1143
Epoch 45/50
19/19 [==============================] - 45s 2s/step - loss: 0.1135 - mae: 0.1135 - val_loss: 0.1157 - val_mae: 0.1157
Epoch 46/50
19/19 [==============================] - 46s 2s/step - loss: 0.1123 - mae: 0.1123 - val_loss: 0.1142 - val_mae: 0.1142
Epoch 47/50
19/19 [==============================] - 47s 2s/step - loss: 0.1115 - mae: 0.1115 - val_loss: 0.1144 - val_mae: 0.1144
Epoch 48/50
19/19 [==============================] - 46s 2s/step - loss: 0.1107 - mae: 0.1107 - val_loss: 0.1161 - val_mae: 0.1161
Epoch 49/50
19/19 [==============================] - 44s 2s/step - loss: 0.1103 - mae: 0.1103 - val_loss: 0.1153 - val_mae: 0.1153
Epoch 50/50
19/19 [==============================] - 45s 2s/step - loss: 0.1094 - mae: 0.1094 - val_loss: 0.1147 - val_mae: 0.1147

In [ ]:
#     model = Sequential()
#     model.add(LSTM(64, activation='relu', input_shape=(train_X.shape[1], train_X.shape[2]), return_sequences=True))
#     model.add(LSTM(32, activation='relu', return_sequences=False))
#     model.add(Dropout(0.2))
#     model.add(Dense(train_y.shape[1]))
#     model.compile(optimizer='adam', loss=SMAPE)

In [238]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_2 (LSTM)                (None, 32)                4864
_________________________________________________________________
dense_2 (Dense)              (None, 120)               3960
_________________________________________________________________
reshape_2 (Reshape)          (None, 24, 5)             0
=================================================================
Total params: 8,824
Trainable params: 8,824
Non-trainable params: 0
_________________________________________________________________

In [239]:
#######################
prediction=np.zeros((num_power, end_, num_features))
new_test_x=train_x

for i in range(end_//output_window):
    start_=i*output_window
    next_=model.predict(new_test_x[ : , -input_window:, :])
    new_test_x = tf.concat([new_test_x, next_], axis=1)
    print(new_test_x.shape)
    prediction[:, start_: start_ + output_window, :]= next_
    
    
prediction =prediction *size + mini

(60, 1992, 5)
(60, 2016, 5)
(60, 2040, 5)
(60, 2064, 5)
(60, 2088, 5)
(60, 2112, 5)
(60, 2136, 5)

In [240]:
# def SMAPE(true, pred):
#     return np.mean((np.abs(true-pred))*2/(np.abs(true) + np.abs(pred)))*100

# print(SMAPE(tt,prediction))

In [241]:
submission['answer']=prediction.reshape([-1,num_features])
submission

          num_date_time       answer
0       1 2020-08-25 00  1630.334526
1       1 2020-08-25 01  1679.570237
2       1 2020-08-25 02  1678.407555
3       1 2020-08-25 03  1653.320191
4       1 2020-08-25 04  1578.241031
...                 ...          ...
10075  60 2020-08-31 19  1896.783019
10076  60 2020-08-31 20  1749.436347
10077  60 2020-08-31 21  1577.192240
10078  60 2020-08-31 22  1443.731888
10079  60 2020-08-31 23  1490.330990

[10080 rows x 2 columns]

In [242]:
submission.shape

(10080, 2)

In [243]:
submission.to_csv('baseline_submission6.csv', index=False)