In [31]:
#Library Imports
import numpy as np
import pandas as pd
import math
import os
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error

#######딥러닝 라이브러리##########
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Reshape, GRU, RNN

tf.keras.backend.set_floatx('float64')

In [32]:
train=pd.read_csv('train.csv',encoding = 'cp949')
train['date_time'] = pd.to_datetime(train['date_time'])

test=pd.read_csv('test.csv', encoding = 'cp949')
test['date_time'] = pd.to_datetime(test['date_time'])

submission=pd.read_csv('sample_submission.csv', encoding = 'cp949')

In [33]:
#train.shape 122400 X 10
#60개의 건물 X 85일 24시간 =122400
train

,num,date_time,전력사용량(kWh),기온(°C),풍속(m/s),습도(%),강수량(mm),일조(hr),비전기냉방설비운영,태양광보유
0,1,2020-06-01 00:00:00,8179.056,17.6,2.5,92.0,0.8,0.0,0.0,0.0
1,1,2020-06-01 01:00:00,8135.640,17.7,2.9,91.0,0.3,0.0,0.0,0.0
2,1,2020-06-01 02:00:00,8107.128,17.5,3.2,91.0,0.0,0.0,0.0,0.0
3,1,2020-06-01 03:00:00,8048.808,17.1,3.2,91.0,0.0,0.0,0.0,0.0
4,1,2020-06-01 04:00:00,8043.624,17.0,3.3,92.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
122395,60,2020-08-24 19:00:00,4114.368,27.8,2.3,68.0,0.0,0.7,1.0,1.0
122396,60,2020-08-24 20:00:00,3975.696,27.3,1.2,71.0,0.0,0.0,1.0,1.0
122397,60,2020-08-24 21:00:00,3572.208,27.3,1.8,71.0,0.0,0.0,1.0,1.0
122398,60,2020-08-24 22:00:00,3299.184,27.1,1.8,74.0,0.0,0.0,1.0,1.0
122399,60,2020-08-24 23:00:00,3204.576,27.1,2.6,75.0,0.0,0.0,1.0,1.0

In [34]:
#train.shape 2040 X 10
#1개의 건물 X 85일 24시간 =2040

train

,num,date_time,전력사용량(kWh),기온(°C),풍속(m/s),습도(%),강수량(mm),일조(hr),비전기냉방설비운영,태양광보유
0,1,2020-06-01 00:00:00,8179.056,17.6,2.5,92.0,0.8,0.0,0.0,0.0
1,1,2020-06-01 01:00:00,8135.640,17.7,2.9,91.0,0.3,0.0,0.0,0.0
2,1,2020-06-01 02:00:00,8107.128,17.5,3.2,91.0,0.0,0.0,0.0,0.0
3,1,2020-06-01 03:00:00,8048.808,17.1,3.2,91.0,0.0,0.0,0.0,0.0
4,1,2020-06-01 04:00:00,8043.624,17.0,3.3,92.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
122395,60,2020-08-24 19:00:00,4114.368,27.8,2.3,68.0,0.0,0.7,1.0,1.0
122396,60,2020-08-24 20:00:00,3975.696,27.3,1.2,71.0,0.0,0.0,1.0,1.0
122397,60,2020-08-24 21:00:00,3572.208,27.3,1.8,71.0,0.0,0.0,1.0,1.0
122398,60,2020-08-24 22:00:00,3299.184,27.1,1.8,74.0,0.0,0.0,1.0,1.0
122399,60,2020-08-24 23:00:00,3204.576,27.1,2.6,75.0,0.0,0.0,1.0,1.0

In [35]:
#test.shape 10080 X 9
#60개의 건물 X 7일 24시간 =10080
test

,num,date_time,기온(°C),풍속(m/s),습도(%),"강수량(mm, 6시간)","일조(hr, 3시간)",비전기냉방설비운영,태양광보유
0,1,2020-08-25 00:00:00,27.8,1.5,74.0,0.0,0.0,NaN,NaN
1,1,2020-08-25 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2020-08-25 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2020-08-25 03:00:00,27.3,1.1,78.0,NaN,0.0,NaN,NaN
4,1,2020-08-25 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
10075,60,2020-08-31 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10076,60,2020-08-31 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10077,60,2020-08-31 21:00:00,27.9,4.1,68.0,NaN,0.0,1.0,1.0
10078,60,2020-08-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10079,60,2020-08-31 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **딥러닝 모델(전력사용량만 변수로 사용)**

In [36]:
import datetime as dt

In [37]:
train['weekday'] = train['date_time'].dt.weekday + 1
train['hour'] = train['date_time'].dt.hour

test['weekday'] = test['date_time'].dt.weekday + 1
test['hour'] = test['date_time'].dt.hour

In [38]:
from sklearn.cluster import k_means
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

d_list = []
for i in range(1, 61):
    d = train[train['num'] == i].copy()
    d['전력사용량(kWh)'] = scaler.fit_transform(d['전력사용량(kWh)'].values.reshape(-1,1))
    d_ = d.groupby(['weekday', 'hour'])['전력사용량(kWh)'].mean().unstack()
    d_list.append(d_.to_numpy())

In [39]:
##############전력사용량(kWh) 정규화####################################

mini=train.iloc[:,2].min()
size=train.iloc[:,2].max()-train.iloc[:,2].min()
train.iloc[:,2]=(train.iloc[:,2]-mini)/size

In [40]:
train

,num,date_time,전력사용량(kWh),기온(°C),풍속(m/s),습도(%),강수량(mm),일조(hr),비전기냉방설비운영,태양광보유,weekday,hour
0,1,2020-06-01 00:00:00,0.461072,17.6,2.5,92.0,0.8,0.0,0.0,0.0,1,0
1,1,2020-06-01 01:00:00,0.458624,17.7,2.9,91.0,0.3,0.0,0.0,0.0,1,1
2,1,2020-06-01 02:00:00,0.457017,17.5,3.2,91.0,0.0,0.0,0.0,0.0,1,2
3,1,2020-06-01 03:00:00,0.453729,17.1,3.2,91.0,0.0,0.0,0.0,0.0,1,3
4,1,2020-06-01 04:00:00,0.453437,17.0,3.3,92.0,0.0,0.0,0.0,0.0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,60,2020-08-24 19:00:00,0.231936,27.8,2.3,68.0,0.0,0.7,1.0,1.0,1,19
122396,60,2020-08-24 20:00:00,0.224119,27.3,1.2,71.0,0.0,0.0,1.0,1.0,1,20
122397,60,2020-08-24 21:00:00,0.201373,27.3,1.8,71.0,0.0,0.0,1.0,1.0,1,21
122398,60,2020-08-24 22:00:00,0.185982,27.1,1.8,74.0,0.0,0.0,1.0,1.0,1,22
122399,60,2020-08-24 23:00:00,0.180649,27.1,2.6,75.0,0.0,0.0,1.0,1.0,1,23

In [43]:
####################################################

input_window = 996 #임의의 수
output_window = 24 #168 7일 24시간
window = 12 #window는 12시간 마다는 12시간 마다
num_features = 1 #베이스라인은 feature를 하나만 사용했습니다.
num_power = 60 #건물개수
end_=168 
lstm_units=32
dropout=0.2
EPOCH=30
BATCH_SIZE=128

In [44]:
#train을 tensor로 변경 (60, 24*85, 1)
train_x=tf.reshape(train.iloc[:,2].values, [num_power, 24*85, num_features])
print(f'train_x.shape:{train_x.shape}')

train_x.shape:(60, 2040, 1)

In [45]:
#train_window_x np.zeros를 만듬 (60, 85, 996, 1)
train_window_x= np.zeros(( train_x.shape[0], (train_x.shape[1]-(input_window + output_window))//window, input_window, num_features)) 
train_window_y= np.zeros(( train_x.shape[0], (train_x.shape[1]-(input_window + output_window))//window, output_window, num_features))
print(f'train_window_x.shape:{train_window_x.shape}')
print(f'train_window_y.shape:{train_window_y.shape}')

train_window_x.shape:(60, 85, 996, 1)
train_window_y.shape:(60, 85, 24, 1)

In [46]:
#train_window_x에 train값 채워넣기
for example in range(train_x.shape[0]):
    
    for start in range(0, train_x.shape[1]-(input_window+output_window), window):
        end=start+input_window
        train_window_x[example, start//window, :] = train_x[example, start: end               , :]
        train_window_y[example, start//window, :] = train_x[example, end  : end+ output_window, :]

In [47]:
#new_train_x, reshape통해 lstm에 알맞은 형태로 집어넣기
new_train_x=tf.reshape(train_window_x, [-1, input_window, num_features])
new_train_y=tf.reshape(train_window_y, [-1, output_window,num_features])
print(f'new_train_x.shape:{new_train_x.shape}')
print(f'new_train_y.shape:{new_train_y.shape}')

new_train_x.shape:(5100, 996, 1)
new_train_y.shape:(5100, 24, 1)

In [48]:
from sklearn.model_selection import KFold
from numpy.random import seed

In [50]:
# folds=3
# repeats=3
# epochsize=20
# drop=0.5
# kfold = KFold(n_splits=folds, shuffle=True)

# save_best_only=tf.keras.callbacks.ModelCheckpoint(filepath="lstm_model.h5", monitor='val_loss', save_best_only=True)
# early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=20)
# reduceLR = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10)


# for k in range(repeats):
#     for train_ind, test_ind in kfold.split(new_train_x, new_train_y):
#         seed(2021)
#         tf.random.set_seed(2021)

#         input_layer = keras.layers.Input(new_train_x.shape[1:])
#         model1 = keras.layers.LSTM(32, return_sequences=False, recurrent_dropout=dropout)(input_layer)

#         output_layer = keras.layers.Dense(output_window * num_features, kernel_initializer=tf.initializers.zeros())(model1)

#         model = keras.models.Model(inputs=input_layer, outputs=output_layer)


#         model.compile(loss='mae',
#                       optimizer='rmsprop',
#                       metrics=['mae'])

#         model.fit(new_train_x, new_train_y, epochs=EPOCH, batch_size=BATCH_SIZE, validation_split = 0.2, verbose=1,
#           callbacks=[early_stop, save_best_only , reduceLR])

        
        
        
#     print(f'\n\n********    {k+1}번 러닝 완료    *********\n\n')

In [52]:
#####층 쌓기###########


model=Sequential([
LSTM(lstm_units, return_sequences=False, recurrent_dropout=dropout),
Dense(output_window * num_features, kernel_initializer=tf.initializers.zeros()), 
Reshape([output_window, num_features])
])
#######Compile 구성하기################


model.compile(optimizer='rmsprop', loss='mae', metrics=['mae'])
# # 에포크가 끝날 때마다 점(.)을 출력해 훈련 진행 과정을 표시합니다
# class PrintDot(tf.keras.callbacks.Callback):
#     def on_epoch_end(self, epoch, logs):
#         if epoch % 10 == 0: print('')
#         print('.', end='')

#가장 좋은 성능을 낸 val_loss가 적은 model만 남겨 놓았습니다.
save_best_only=tf.keras.callbacks.ModelCheckpoint(filepath="lstm_model.h5", monitor='val_loss', save_best_only=True)


early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=20)

#검증 손실이 10epoch 동안 좋아지지 않으면 학습률을 0.1 배로 재구성하는 명령어입니다.
reduceLR = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10)

######################
model.fit(new_train_x, new_train_y, epochs=EPOCH, batch_size=BATCH_SIZE, validation_split = 0.2, verbose=1,
          callbacks=[early_stop, save_best_only , reduceLR])

WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
Epoch 1/30
32/32 [==============================] - 83s 3s/step - loss: 0.0677 - mae: 0.0677 - val_loss: 0.0457 - val_mae: 0.0457
Epoch 2/30
32/32 [==============================] - 81s 3s/step - loss: 0.0402 - mae: 0.0402 - val_loss: 0.0445 - val_mae: 0.0445
Epoch 3/30
32/32 [==============================] - 81s 3s/step - loss: 0.0393 - mae: 0.0393 - val_loss: 0.0305 - val_mae: 0.0305
Epoch 4/30
32/32 [==============================] - 80s 3s/step - loss: 0.0383 - mae: 0.0383 - val_loss: 0.0339 - val_mae: 0.0339
Epoch 5/30
32/32 [==============================] - 80s 2s/step - loss: 0.0374 - mae: 0.0374 - val_loss: 0.0291 - val_mae: 0.0291
Epoch 6/30
32/32 [==============================] - 81s 3s/step - loss: 0.0372 - mae: 0.0372 - val_loss: 0.0242 - val_mae: 0.0242
Epoch 7/30
32/32 [==============================] - 82s 3s/step - loss: 0.0359 - mae: 0.0359 - val_loss: 0.0250 - val_mae: 0.0250
Epoch 8/30
32/32 [==============================] - 80s 3s/step - loss: 0.0358 - mae: 0.0358 - val_loss: 0.0247 - val_mae: 0.0247
Epoch 9/30
32/32 [==============================] - 79s 2s/step - loss: 0.0346 - mae: 0.0346 - val_loss: 0.0255 - val_mae: 0.0255
Epoch 10/30
32/32 [==============================] - 80s 3s/step - loss: 0.0336 - mae: 0.0336 - val_loss: 0.0239 - val_mae: 0.0239
Epoch 11/30
32/32 [==============================] - 79s 2s/step - loss: 0.0320 - mae: 0.0320 - val_loss: 0.0231 - val_mae: 0.0231
Epoch 12/30
32/32 [==============================] - 80s 2s/step - loss: 0.0282 - mae: 0.0282 - val_loss: 0.0200 - val_mae: 0.0200
Epoch 13/30
32/32 [==============================] - 80s 2s/step - loss: 0.0258 - mae: 0.0258 - val_loss: 0.0176 - val_mae: 0.0176
Epoch 14/30
32/32 [==============================] - 78s 2s/step - loss: 0.0236 - mae: 0.0236 - val_loss: 0.0206 - val_mae: 0.0206
Epoch 15/30
32/32 [==============================] - 78s 2s/step - loss: 0.0220 - mae: 0.0220 - val_loss: 0.0161 - val_mae: 0.0161
Epoch 16/30
32/32 [==============================] - 79s 2s/step - loss: 0.0215 - mae: 0.0215 - val_loss: 0.0187 - val_mae: 0.0187
Epoch 17/30
32/32 [==============================] - 79s 2s/step - loss: 0.0207 - mae: 0.0207 - val_loss: 0.0180 - val_mae: 0.0180
Epoch 18/30
32/32 [==============================] - 77s 2s/step - loss: 0.0202 - mae: 0.0202 - val_loss: 0.0167 - val_mae: 0.0167
Epoch 19/30
32/32 [==============================] - 78s 2s/step - loss: 0.0196 - mae: 0.0196 - val_loss: 0.0157 - val_mae: 0.0157
Epoch 20/30
32/32 [==============================] - 78s 2s/step - loss: 0.0195 - mae: 0.0195 - val_loss: 0.0167 - val_mae: 0.0167
Epoch 21/30
32/32 [==============================] - 77s 2s/step - loss: 0.0188 - mae: 0.0188 - val_loss: 0.0160 - val_mae: 0.0160
Epoch 22/30
32/32 [==============================] - 78s 2s/step - loss: 0.0191 - mae: 0.0191 - val_loss: 0.0148 - val_mae: 0.0148
Epoch 23/30
32/32 [==============================] - 77s 2s/step - loss: 0.0185 - mae: 0.0185 - val_loss: 0.0163 - val_mae: 0.0163
Epoch 24/30
32/32 [==============================] - 79s 2s/step - loss: 0.0185 - mae: 0.0185 - val_loss: 0.0151 - val_mae: 0.0151
Epoch 25/30
32/32 [==============================] - 78s 2s/step - loss: 0.0183 - mae: 0.0183 - val_loss: 0.0137 - val_mae: 0.0137
Epoch 26/30
32/32 [==============================] - 78s 2s/step - loss: 0.0179 - mae: 0.0179 - val_loss: 0.0141 - val_mae: 0.0141
Epoch 27/30
32/32 [==============================] - 78s 2s/step - loss: 0.0179 - mae: 0.0179 - val_loss: 0.0143 - val_mae: 0.0143
Epoch 28/30
32/32 [==============================] - 77s 2s/step - loss: 0.0177 - mae: 0.0177 - val_loss: 0.0137 - val_mae: 0.0137
Epoch 29/30
32/32 [==============================] - 77s 2s/step - loss: 0.0176 - mae: 0.0176 - val_loss: 0.0145 - val_mae: 0.0145
Epoch 30/30
32/32 [==============================] - 78s 2s/step - loss: 0.0178 - mae: 0.0178 - val_loss: 0.0141 - val_mae: 0.0141

In [53]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_1 (LSTM)                (None, 32)                4352
_________________________________________________________________
dense_1 (Dense)              (None, 24)                792
_________________________________________________________________
reshape_1 (Reshape)          (None, 24, 1)             0
=================================================================
Total params: 5,144
Trainable params: 5,144
Non-trainable params: 0
_________________________________________________________________

In [54]:
#######################
prediction=np.zeros((num_power, end_, num_features))
new_test_x=train_x

for i in range(end_//output_window):
    start_=i*output_window
    next_=model.predict(new_test_x[ : , -input_window:, :])
    new_test_x = tf.concat([new_test_x, next_], axis=1)
    print(new_test_x.shape)
    prediction[:, start_: start_ + output_window, :]= next_
    
    
prediction =prediction *size + mini

(60, 2064, 1)
(60, 2088, 1)
(60, 2112, 1)
(60, 2136, 1)
(60, 2160, 1)
(60, 2184, 1)
(60, 2208, 1)

In [73]:
tt = new_train_y.numpy()
tt.reshape(60,-1,1)
tt.shape

(5100, 24, 1)

In [76]:
new_train_x

<tf.Tensor: shape=(5100, 996, 1), dtype=float64, numpy=
array([[[0.46107178],
        [0.45862432],
        [0.45701703],
        ...,
        [0.47571999],
        [0.47524511],
        [0.47630446]],

       [[0.45599422],
        [0.45676133],
        [0.45595769],
        ...,
        [0.4768524 ],
        [0.47740034],
        [0.47641405]],

       [[0.44649662],
        [0.44477975],
        [0.44353775],
        ...,
        [0.4779848 ],
        [0.47882498],
        [0.47845968]],

       ...,

       [[0.16730381],
        [0.16479547],
        [0.16094773],
        ...,
        [0.20436879],
        [0.21425603],
        [0.24998161]],

       [[0.20712066],
        [0.20977512],
        [0.21359851],
        ...,
        [0.2083383 ],
        [0.19489555],
        [0.18174503]],

       [[0.1619462 ],
        [0.15965703],
        [0.15797669],
        ...,
        [0.20414962],
        [0.20680407],
        [0.23332429]]])>

In [69]:
def SMAPE(true, pred):
    return np.mean((np.abs(true-pred))*2/(np.abs(true) + np.abs(pred)))*100

print(SMAPE(tt,prediction))

ValueError: operands could not be broadcast together with shapes (5100,24,1) (60,168,1)

In [74]:
submission['answer']=prediction.reshape([-1,1])
submission

          num_date_time       answer
0       1 2020-08-25 00  8356.785129
1       1 2020-08-25 01  8363.638394
2       1 2020-08-25 02  8295.791957
3       1 2020-08-25 03  8268.152263
4       1 2020-08-25 04  8278.357175
...                 ...          ...
10075  60 2020-08-31 19  3241.001914
10076  60 2020-08-31 20  2957.554730
10077  60 2020-08-31 21  2571.261598
10078  60 2020-08-31 22  2323.413199
10079  60 2020-08-31 23  2294.095621

[10080 rows x 2 columns]

In [75]:
submission.to_csv('baseline_submission3.csv', index=False)